### PR TITLE
Make __wasi_linkcount_t a uint64_t

### PR DESCRIPTION
**Pull request by cjihrig**
Refs: https://github.com/WebAssembly/WASI/pull/127

### CODE REVIEW

**Comment by cjihrig** [comment]
Ping @sunfishcode?

**Comment by sunfishcode** [comment]
We need to figure out the right way to coordinate this with the overall switch to `wasi_snapshot_preview0`. Would it make sense to have a branch that we can make all the changes on, and then merge them all into master at once?

**Comment by cjihrig** [comment]
That sounds like a good approach. That would include this PR, https://github.com/CraneStation/wasi-libc/pull/106, and something for https://github.com/WebAssembly/WASI/pull/125 (I was going to PR that as well, but wanted to see how this PR went first). I *think* those are all of the changes for the current snapshot.

**Comment by sunfishcode** [comment]
Ok, I've now created https://github.com/CraneStation/wasi-libc/tree/wasi_snapshot_preview1 so we can do PRs there.

**Comment by cjihrig** [comment]
Thanks. I've updated this PR to target that branch.

**Pull request merged**
